export interface InventoryCategory {
  id: string
  name: string
  units: string[]
  defaultUnit: string
  products: string[]
}

export const INVENTORY_CATEGORIES: InventoryCategory[] = [
  {
    id: 'produse-bucata',
    name: 'PRODUSE LA BUCATA',
    units: ['buc.', 'g.', 'tava'],
    defaultUnit: 'buc.',
    products: [
      'Amandina',
      'Ora 12',
      'Ecler frisca',
      'Ecler vanilie farta',
      'Ecler fistic',
      'Ecler cafea',
      'Ecler ciocolata',
      'Ecler caramel sarat',
      'Savarine',
      'Blanche',
      'Kremsnit',
      'Extraordinar',
      'Mousse X3',
      'Mousse fructe de padure',
      'Tiramisu cupa',
      'Mura',
      'Mousse Snyx / felie',
      'Visine pe tocuri',
      'Mambo',
      'Paris Brest',
      'Pavlova',
      'Cannolo siciliani',
      'Mini tort amandina',
      'Mini tort inima',
      'Mousse fistic',
      'Mousse Rocher',
      'Pina Colada',
      'Pearl',
      'Mousse Kaffa',
    ],
  },
  {
    id: 'produse-kg',
    name: 'PRODUSE KG',
    units: ['tava', 'platou', 'rand'],
    defaultUnit: 'tava',
    products: [
      'Saratele',
      'Placinta cu mere dulce',
      'Placinta cu branza',
      'Gobs',
      'Turtite cu stafide',
      'Pricomigdale',
      'Cornulete',
      'Cracker vanzare',
      'Cracker cafea',
      'Minichoux',
      'Mini eclere',
      'Mini eclere cu fistic',
      'Mini Paris Brest',
      'Minitarte',
      'Raffaella',
      'Caramel',
      'Meringue',
      'Ardealul',
      'Tavalita',
      'Rulouri vanilie',
      'Rulouri ciocolata',
      'Praj cu branza si lam',
      'Linzer',
      'Alba ca zapada',
      'Dubai',
      'Dubai fara zahar',
      'Rulada Dubai',
      'Mini Excellent',
      'Mini Rocher',
      'Mix fructe',
    ],
  },
  {
    id: 'torturi-tarte',
    name: 'TORTURI SI TARTE',
    units: ['felie', 'buc.'],
    defaultUnit: 'felie',
    products: [
      'Tort belcolade intreg',
      'Tort belcolade feliat',
      'Tort fructe de padure',
      'Tort mousse X3',
      'Tort de zmeure',
      'Tort de mure',
      'Tort Ness feliat',
      'Tort amarena',
      'Tort fara zahar',
      'Tort padurea neagra',
      'Tort Snyx',
      'Tort Oreo',
      'Tarta cu branza',
      'Bavareza cu portocale',
      'Tort de biscuiti',
      'Tort Mambo',
      'Tort fistic, ciocolata, zmeure',
      'Tort Ferrero Rocher',
      'Cinnamon clasic',
      'Cinnamon fistic',
      'Cinnamon cafea',
    ],
  },
  {
    id: 'patiserie',
    name: 'PATISERIE',
    units: ['tava', 'platou'],
    defaultUnit: 'tava',
    products: [
      'Pateuri cu branza',
      'Strudele cu mere',
      'Rulouri cu branza',
      'Mini pateuri',
      'Mini ciuperci',
      'Mini carne',
      'Cozonac',
      'Pasca',
      'Croissant zmeure',
      'Croissant fistic',
    ],
  },
  {
    id: 'altele',
    name: 'ALTELE',
    units: ['buc.', 'g.'],
    defaultUnit: 'buc.',
    products: [
      'Alune',
      'Mucenici',
      'Cozonac fara zahar',
    ],
  },
  {
    id: 'post',
    name: 'POST',
    units: ['tava', 'platou', 'rand'],
    defaultUnit: 'tava',
    products: [
      'Minciunele',
      'Placinta cu dovleac',
      'Placinta cu mere',
      'Negresa',
      'Baclava',
      'Sarailie',
      'Sarailie fara zahar',
      'Salam de biscuiti',
    ],
  },
]


